import pandas as pd
import numpy as np
import time
from datetime import datetime, time, timedelta
from pandas.tseries.holiday import Holiday, AbstractHolidayCalendar

class Initialize(object):

    def getDataSet(self,c):
            if c==0:
                class MyCalendar(AbstractHolidayCalendar):
                        rules = [Holiday('holiday1', month=1, day=3),Holiday('holiday2', month=1, day=4),
                                 Holiday('holiday1', month=1, day=12),Holiday('holiday2', month=1, day=16),
                                 Holiday('holiday1', month=1, day=18),Holiday('holiday2', month=1, day=22),
                                 Holiday('holiday1', month=1, day=26)]

                dataSet = {"position":pd.DataFrame(),
                          }

                parameters = {#"""*************** PARAMETERS FOR CustomTimeRule *****************""""
                              "startDate": '1/1/2018', "endDate": '2/1/2018',
                              "startTime":'9:00', "endTime":'16:00',
                              "holidays" : ['2018-01-03','2018-01-04','2018-01-12', '2018-01-16','2018-01-18','2018-01-22','2018-01-26'],
                              "weekmask" : 'Mon Tue Wed Thu Fri',
                              "calendar" : MyCalendar(), "frequency":'D', "sample":'1',
                              #"""*************** PARAMETERS FOR QuantQuestTimeRule *****************""""
                              "cachedFolderName" : 'Folder1', "dataSetId" : 'trainingW5_trainingData', "downloadLocation" : 'data.txt',
                              "testcachedFolderName": 'test_folder1', "testdataSetId":"test_folder2",
                              #"""*************** PARAMETERS FOR USTimeRule *****************""""
                              "startDateustimerule": '1/1/2018', "endDateustimerule": '2/1/2018',
                              "startTimeustimerule":'9:00', "endTimeustimerule":'16:00',
                              #using same parameters as CustomTimeRule
                              #"""*************** PARAMETERS FOR NSETimeRule *****************""""
                              "startDatensetimerule": '11/1/2018', "endDatensetimerule": '12/1/2018',
                              "startTimensetimerule":'9:00', "endTimensetimerule":'16:00',
                              #using same parameters as CustomTimeRule
                              }

                results = { #"""****************** RESULTS FOR CustomTimeRule*************"""
                            'createBusinessDaySeries'                          :   [pd.tslib.Timestamp(' 2018-01-01 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-05 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-08 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-09 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-10 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-11 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-15 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-17 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-19 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-23 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-24 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-25 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-29 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-30 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-31 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-02-01 00:00:00 ')],
                            'createBusinessHourSeries'                         :   [],
                            'createBusinessMinSeries'                          :   [],
                            'createBusinessSecSeries'                          :   [],
                            #"""*************** RESULTS FOR QuantQuestTimeRule *****************""""
                            'getFileName'                                      :   "Folder1/trainingW5_trainingData/date_list.txt",
                            'downloadFile'                                     :   True,
                            'emitTimeToTradeforQuantQuestTimeRule'             :   [0.0],
                            #"""*************** RESULTS FOR USTimeRule *****************""""
                            'createBusinessDaySeriesforustimerule'             :   [pd.tslib.Timestamp(' 2018-01-02 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-03 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-04 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-05 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-08 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-09 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-10 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-11 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-12 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-16 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-17 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-18 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-19 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-22 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-23 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-24 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-25 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-26 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-29 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-30 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-31 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-02-01 00:00:00 ')],
                            'createBusinessHourSeriesforustimerule'            :   [],
                            'createBusinessMinSeriesforustimerule'             :   [],
                            'createBusinessSecSeriesforustimerule'             :   [],
                            #"""*************** RESULTS FOR NSETimeRule *****************""""
                            'getNSEHolidays'                                   :   [0.0],
                            'createBusinessDaySeriesfornsetimerule'            :   [pd.tslib.Timestamp(' 2018-11-01 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-02 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-05 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-06 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-09 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-12 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-13 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-14 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-15 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-16 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-19 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-20 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-21 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-22 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-26 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-27 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-28 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-29 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-30 00:00:00 ')],
                            'createBusinessHourSeriesfornsetimerule'           :   [],
                            'createBusinessMinSeriesfornsetimerule'            :   [],
                            'createBusinessSecSeriesfornsetimerule'            :   [],
                          }

                return {"dataSet":dataSet, "results":results, "parameters":parameters}

            if c==1:
                class MyCalendar(AbstractHolidayCalendar):
                        rules = [Holiday('holiday1', month=1, day=3),Holiday('holiday2', month=1, day=4)]

                dataSet = {"position":pd.DataFrame(),
                          }

                parameters = {#"""*************** PARAMETERS FOR CustomTimeRule *****************""""
                              "startDate": '1/1/2018', "endDate": '1/10/2018',
                              "startTime":'9:00', "endTime":'16:00',
                              "holidays" : ['2018-01-03','2018-01-04'], "weekmask" : 'Mon Tue Wed Thu Fri',
                              "calendar" : MyCalendar(), "frequency":'H', "sample":'1',
                              #"""*************** PARAMETERS FOR QuantQuestTimeRule *****************""""
                              "cachedFolderName" : 'Folder1', "dataSetId" : 'Folder2', "downloadLocation" : 'data.txt',
                              "testcachedFolderName": 'test_folder1', "testdataSetId":"test_folder2",
                              #"""*************** PARAMETERS FOR USTimeRule *****************""""
                              "startDateustimerule": '1/1/2018', "endDateustimerule": '1/10/2018',
                              "startTimeustimerule":'9:00', "endTimeustimerule":'16:00',
                              #using same parameters as CustomTimeRule
                              #"""*************** PARAMETERS FOR NSETimeRule *****************""""
                              "startDatensetimerule": '11/1/2018', "endDatensetimerule": '11/10/2018',
                              "startTimensetimerule":'9:00', "endTimensetimerule":'16:00',
                              #using same parameters as CustomTimeRule
                              }

                results = { #"""****************** RESULTS FOR CustomTimeRule*************"""
                            'createBusinessDaySeries'                          :   [pd.tslib.Timestamp(' 2018-01-01 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-05 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-08 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-09 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-10 00:00:00 ')],
                            'createBusinessHourSeries'                         :   [pd.tslib.Timestamp(' 2018-01-01 09:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 10:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 11:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 12:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 13:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 14:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 15:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 10:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 11:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 12:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 13:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 14:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 15:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-05 09:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-05 10:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-05 11:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-05 12:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-05 13:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-05 14:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-05 15:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-08 09:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-08 10:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-08 11:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-08 12:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-08 13:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-08 14:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-08 15:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-09 09:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-09 10:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-09 11:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-09 12:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-09 13:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-09 14:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-09 15:00:00 ')],
                            'createBusinessMinSeries'                          :   [],
                            'createBusinessSecSeries'                          :   [],
                            #"""*************** RESULTS FOR QuantQuestTimeRule *****************""""
                            'getFileName'                                      :   "Folder1/Folder2/date_list.txt",
                            'downloadFile'                                     :   False,
                            'emitTimeToTradeforQuantQuestTimeRule'             :   [0.0],
                            #"""*************** RESULTS FOR USTimeRule *****************""""
                            'createBusinessDaySeriesforustimerule'             :   [pd.tslib.Timestamp(' 2018-01-02 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-03 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-04 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-05 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-08 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-09 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-10 00:00:00 ')],
                            'createBusinessHourSeriesforustimerule'            :   [pd.tslib.Timestamp(' 2018-01-02 09:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 10:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 11:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 12:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 13:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 14:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 15:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-03 09:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-03 10:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-03 11:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-03 12:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-03 13:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-03 14:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-03 15:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-04 09:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-04 10:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-04 11:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-04 12:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-04 13:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-04 14:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-04 15:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-05 09:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-05 10:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-05 11:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-05 12:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-05 13:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-05 14:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-05 15:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-08 09:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-08 10:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-08 11:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-08 12:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-08 13:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-08 14:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-08 15:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-09 09:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-09 10:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-09 11:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-09 12:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-09 13:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-09 14:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-09 15:00:00 ')],
                            'createBusinessMinSeriesforustimerule'             :   [],
                            'createBusinessSecSeriesforustimerule'             :   [],
                            #"""*************** RESULTS FOR NSETimeRule *****************""""
                            'getNSEHolidays'                                   :   [0.0],
                            'createBusinessDaySeriesfornsetimerule'            :   [pd.tslib.Timestamp(' 2018-11-01 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-02 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-05 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-06 00:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-09 00:00:00 ')],
                            'createBusinessHourSeriesfornsetimerule'           :   [pd.tslib.Timestamp(' 2018-11-01 09:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 10:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 11:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 12:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 13:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 14:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 15:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-02 09:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-02 10:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-02 11:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-02 12:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-02 13:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-02 14:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-02 15:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-05 09:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-05 10:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-05 11:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-05 12:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-05 13:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-05 14:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-05 15:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-06 09:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-06 10:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-06 11:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-06 12:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-06 13:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-06 14:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-06 15:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-09 09:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-09 10:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-09 11:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-09 12:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-09 13:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-09 14:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-09 15:00:00 ')],
                            'createBusinessMinSeriesfornsetimerule'            :   [],
                            'createBusinessSecSeriesfornsetimerule'            :   [],
                          }

                return {"dataSet":dataSet, "results":results, "parameters":parameters}

            if c==2:
                class MyCalendar(AbstractHolidayCalendar):
                        rules = [Holiday('holiday1', month=1, day=3),Holiday('holiday2', month=1, day=4)]

                dataSet = {"position":pd.DataFrame(),
                          }

                parameters = {#"""*************** PARAMETERS FOR CustomTimeRule *****************""""
                              "startDate": '1/1/2018', "endDate": '1/1/2018',
                              "startTime":'9:00', "endTime":'9:30',
                              "holidays" : ['2018-01-03','2018-01-04'], "weekmask" : 'Mon Tue Wed Thu Fri',
                              "calendar" : MyCalendar(), "frequency":'M', "sample":'1',
                              #"""*************** PARAMETERS FOR QuantQuestTimeRule *****************""""
                              "cachedFolderName" : 'Folder1', "dataSetId" : 'trainingData1', "downloadLocation" : 'data.txt',
                              "testcachedFolderName": 'test_folder1', "testdataSetId":"test_folder2",
                              #"""*************** PARAMETERS FOR USTimeRule *****************""""
                              "startDateustimerule": '1/2/2018', "endDateustimerule": '1/2/2018',
                              "startTimeustimerule":'9:00', "endTimeustimerule":'9:30',
                              #using same parameters as CustomTimeRule
                              #"""*************** PARAMETERS FOR NSETimeRule *****************""""
                              "startDatensetimerule": '11/1/2018', "endDatensetimerule": '11/1/2018',
                              "startTimensetimerule":'9:00', "endTimensetimerule":'9:30',
                              #using same parameters as CustomTimeRule
                              }

                results = { #"""****************** RESULTS FOR CustomTimeRule*************"""
                            'createBusinessDaySeries'                          :   [pd.tslib.Timestamp(' 2018-01-01 00:00:00 ')],
                            'createBusinessHourSeries'                         :   [],
                            'createBusinessMinSeries'                          :   [pd.tslib.Timestamp(' 2018-01-01 09:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:01:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:02:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:03:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:04:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:05:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:06:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:07:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:08:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:09:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:10:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:11:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:12:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:13:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:14:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:15:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:16:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:17:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:18:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:19:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:20:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:21:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:22:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:23:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:24:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:25:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:26:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:27:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:28:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:29:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:30:00 ')],
                            'createBusinessSecSeries'                          :   [0.0],
                            #"""*************** RESULTS FOR QuantQuestTimeRule *****************""""
                            'getFileName'                                      :   [0.0],
                            'downloadFile'                                     :   [0.0],
                            'emitTimeToTradeforQuantQuestTimeRule'             :   [0.0],
                            #"""*************** RESULTS FOR USTimeRule *****************""""
                            'createBusinessDaySeriesforustimerule'             :   [pd.tslib.Timestamp(' 2018-01-02 00:00:00 ')],
                            'createBusinessHourSeriesforustimerule'            :   [],
                            'createBusinessMinSeriesforustimerule'             :   [pd.tslib.Timestamp(' 2018-01-02 09:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:01:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:02:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:03:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:04:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:05:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:06:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:07:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:08:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:09:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:10:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:11:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:12:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:13:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:14:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:15:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:16:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:17:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:18:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:19:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:20:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:21:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:22:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:23:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:24:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:25:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:26:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:27:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:28:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:29:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:30:00 ')],
                            'createBusinessSecSeriesforustimerule'             :   [],
                            #"""*************** RESULTS FOR NSETimeRule *****************""""
                            'getNSEHolidays'                                   :   [0.0],
                            'createBusinessDaySeriesfornsetimerule'            :   [pd.tslib.Timestamp(' 2018-11-01 00:00:00 ')],
                            'createBusinessHourSeriesfornsetimerule'           :   [],
                            'createBusinessMinSeriesfornsetimerule'            :   [pd.tslib.Timestamp(' 2018-11-01 09:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:01:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:02:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:03:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:04:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:05:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:06:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:07:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:08:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:09:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:10:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:11:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:12:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:13:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:14:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:15:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:16:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:17:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:18:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:19:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:20:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:21:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:22:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:23:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:24:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:25:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:26:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:27:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:28:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:29:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:30:00 ')],
                            'createBusinessSecSeriesfornsetimerule'            :   [],
                          }

                return {"dataSet":dataSet, "results":results, "parameters":parameters}

            if c==3:
                class MyCalendar(AbstractHolidayCalendar):
                        rules = [Holiday('holiday1', month=1, day=3),Holiday('holiday2', month=1, day=4)]

                dataSet = {"position":pd.DataFrame(),
                          }

                parameters = {#"""*************** PARAMETERS FOR CustomTimeRule *****************""""
                              "startDate": '1/1/2018', "endDate": '1/1/2018',
                              "startTime":'9:00', "endTime":'9:01',
                              "holidays" : ['2018-01-03','2018-01-04'], "weekmask" : 'Mon Tue Wed Thu Fri',
                              "calendar" : MyCalendar(), "frequency":'S', "sample":'1',
                              #"""*************** PARAMETERS FOR QuantQuestTimeRule *****************""""
                              "cachedFolderName" : 'Folder1', "dataSetId" : 'trainingData1', "downloadLocation" : 'data.txt',
                              "testcachedFolderName": 'test_folder1', "testdataSetId":"test_folder2",
                              #"""*************** PARAMETERS FOR USTimeRule *****************""""
                              "startDateustimerule": '1/2/2018', "endDateustimerule": '1/2/2018',
                              "startTimeustimerule":'9:00', "endTimeustimerule":'9:01',
                              #using same parameters as CustomTimeRule
                              #"""*************** PARAMETERS FOR NSETimeRule *****************""""
                              "startDatensetimerule": '11/1/2018', "endDatensetimerule": '11/1/2018',
                              "startTimensetimerule":'9:00', "endTimensetimerule":'9:01',
                              #using same parameters as CustomTimeRule
                              }

                results = { #"""****************** RESULTS FOR CustomTimeRule*************"""
                            'createBusinessDaySeries'                          :   [pd.tslib.Timestamp(' 2018-01-01 00:00:00 ')],
                            'createBusinessHourSeries'                         :   [],
                            'createBusinessMinSeries'                          :   [pd.tslib.Timestamp(' 2018-01-01 09:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:01:00 ')],
                            'createBusinessSecSeries'                          :   [pd.tslib.Timestamp(' 2018-01-01 09:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:00:01 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:00:02 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:00:03 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:00:04 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:00:05 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:00:06 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:00:07 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:00:08 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:00:09 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:00:10 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:00:11 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:00:12 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:00:13 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:00:14 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:00:15 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:00:16 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:00:17 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:00:18 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:00:19 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:00:20 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:00:21 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:00:22 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:00:23 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:00:24 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:00:25 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:00:26 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:00:27 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:00:28 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:00:29 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:00:30 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:00:31 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:00:32 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:00:33 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:00:34 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:00:35 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:00:36 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:00:37 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:00:38 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:00:39 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:00:40 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:00:41 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:00:42 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:00:43 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:00:44 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:00:45 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:00:46 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:00:47 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:00:48 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:00:49 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:00:50 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:00:51 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:00:52 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:00:53 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:00:54 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:00:55 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:00:56 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:00:57 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:00:58 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:00:59 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-01 09:01:00 ')],
                            #"""*************** RESULTS FOR QuantQuestTimeRule *****************""""
                            'getFileName'                                      :   [0.0],
                            'downloadFile'                                     :   [0.0],
                            'emitTimeToTradeforQuantQuestTimeRule'             :   [0.0],
                            #"""*************** RESULTS FOR USTimeRule *****************""""
                            'createBusinessDaySeriesforustimerule'             :   [pd.tslib.Timestamp(' 2018-01-02 00:00:00 ')],
                            'createBusinessHourSeriesforustimerule'            :   [],
                            'createBusinessMinSeriesforustimerule'             :   [pd.tslib.Timestamp(' 2018-01-02 09:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:01:00 ')],
                            'createBusinessSecSeriesforustimerule'             :   [pd.tslib.Timestamp(' 2018-01-02 09:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:00:01 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:00:02 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:00:03 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:00:04 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:00:05 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:00:06 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:00:07 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:00:08 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:00:09 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:00:10 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:00:11 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:00:12 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:00:13 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:00:14 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:00:15 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:00:16 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:00:17 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:00:18 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:00:19 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:00:20 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:00:21 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:00:22 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:00:23 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:00:24 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:00:25 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:00:26 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:00:27 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:00:28 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:00:29 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:00:30 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:00:31 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:00:32 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:00:33 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:00:34 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:00:35 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:00:36 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:00:37 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:00:38 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:00:39 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:00:40 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:00:41 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:00:42 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:00:43 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:00:44 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:00:45 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:00:46 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:00:47 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:00:48 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:00:49 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:00:50 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:00:51 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:00:52 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:00:53 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:00:54 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:00:55 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:00:56 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:00:57 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:00:58 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:00:59 '),
                                                                                    pd.tslib.Timestamp(' 2018-01-02 09:01:00 ')],
                            #"""*************** RESULTS FOR NSETimeRule *****************""""
                            'getNSEHolidays'                                   :   [0.0],
                            'createBusinessDaySeriesfornsetimerule'            :   [pd.tslib.Timestamp(' 2018-11-01 00:00:00 ')],
                            'createBusinessHourSeriesfornsetimerule'           :   [],
                            'createBusinessMinSeriesfornsetimerule'            :   [pd.tslib.Timestamp(' 2018-11-01 09:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:01:00 ')],
                            'createBusinessSecSeriesfornsetimerule'            :   [pd.tslib.Timestamp(' 2018-11-01 09:00:00 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:00:01 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:00:02 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:00:03 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:00:04 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:00:05 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:00:06 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:00:07 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:00:08 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:00:09 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:00:10 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:00:11 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:00:12 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:00:13 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:00:14 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:00:15 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:00:16 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:00:17 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:00:18 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:00:19 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:00:20 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:00:21 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:00:22 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:00:23 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:00:24 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:00:25 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:00:26 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:00:27 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:00:28 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:00:29 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:00:30 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:00:31 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:00:32 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:00:33 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:00:34 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:00:35 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:00:36 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:00:37 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:00:38 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:00:39 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:00:40 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:00:41 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:00:42 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:00:43 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:00:44 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:00:45 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:00:46 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:00:47 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:00:48 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:00:49 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:00:50 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:00:51 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:00:52 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:00:53 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:00:54 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:00:55 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:00:56 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:00:57 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:00:58 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:00:59 '),
                                                                                    pd.tslib.Timestamp(' 2018-11-01 09:01:00 ')],
                          }

                return {"dataSet":dataSet, "results":results, "parameters":parameters}
